export default function Vinyl() {
  return (
    <div>
      <svg
        width="70%"
        viewBox="0 0 100 100"
      >
        <circle
          cx="50"
          cy="50"
          r="49"
          fill="lightblue"
          stroke="black"
          strokeWidth="0.1"
        ></circle>
        <circle
          cx="50"
          cy="50"
          r="43"
          fill="grey"
          // stroke="black"
          strokeWidth="0.1"
        ></circle>
        <circle
          cx="50"
          cy="50"
          r="38"
          fill="grey"
          stroke="black"
          strokeWidth="0.1"
        ></circle>
        <circle
          cx="50"
          cy="50"
          r="34"
          fill="grey"
          stroke="black"
          strokeWidth="0.1"
        ></circle>
        <circle
          cx="50"
          cy="50"
          r="27"
          fill="black"
        ></circle>
        <circle
          cx="50"
          cy="50"
          r="16"
          fill="red"
        ></circle>
        <circle
          cx="49.8"
          cy="50.3"
          r="4.5"
          fill="black"
        ></circle>
        <circle
          cx="50"
          cy="50"
          r="4.5"
          fill="white"
        ></circle>
      </svg>
    </div>
  );
}
